# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-19 09:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MapSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('google_maps_key', models.CharField(blank=True, max_length=100)),
                ('default_centerx', models.FloatField(blank=True)),
                ('default_centery', models.FloatField(blank=True)),
                ('default_zoom', models.PositiveSmallIntegerField(default=12)),
            ],
        ),
        migrations.CreateModel(
            name='Overlay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mapname', models.CharField(max_length=255, unique=True)),
                ('extension', models.CharField(max_length=5)),
                ('created', models.DateTimeField(null=True)),
                ('publish', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now_add=True, null=True)),
                ('minx', models.FloatField(blank=True)),
                ('miny', models.FloatField(blank=True)),
                ('maxx', models.FloatField(blank=True)),
                ('maxy', models.FloatField(blank=True)),
                ('centerx', models.FloatField(blank=True)),
                ('centery', models.FloatField(blank=True)),
            ],
            options={
                'ordering': ['mapname'],
            },
        ),
    ]
